In [6]:
import numpy as np

data= np.float_([[0.9526,-0.246,-0.8856],
               [0.5639,0.2379,0.9104]])

data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [7]:
data*10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [8]:
data+data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [11]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [14]:
data1=[6,7.5,8,0,1]
print(data1)
arr1=np.array(data1)
arr1

[6, 7.5, 8, 0, 1]


array([6. , 7.5, 8. , 0. , 1. ])