In [1]:
import numpy as np

data= np.float_([[0.9526,-0.246,-0.8856],
               [0.5639,0.2379,0.9104]])

data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [2]:
data*10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [3]:
data+data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
data1=[6,7.5,8,0,1]
print(data1)
arr1=np.array(data1)
arr1

[6, 7.5, 8, 0, 1]


array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# ndim dkslcaslcksdklc
arr2.ndim

2

In [9]:
y = np.zeros((2, 3, 4))
y.ndim

3

In [10]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3,2))

array([[[9.1e-322, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr=np.array([1,2,3,4,5])

In [19]:
arr.dtype

dtype('int32')

In [20]:
float_arr=arr.astype(np.float64)

In [21]:
float_arr.dtype

dtype('float64')

In [22]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [23]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [25]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)

In [26]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
int_array=np.arange(10)

In [28]:
calibers=np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [29]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
empty_uint32=np.empty(8,dtype='u4')

In [31]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)